############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
weight = 4
name = "Services"

[[main]]
parent = "Services"
name = "Consulting"
url = "/services/consulting"

[[main]]
parent = "Services"
name = "Resources"
url = "/services/resources"

[[main]]
parent = "Services"
name = "Formation"
url = "/services/formation"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
